"""Initial Migration

Revision ID: b35482f16c00
Revises: 
Create Date: 2022-06-06 22:22:19.835259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b35482f16c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cust', table_name='account_info')
    op.drop_table('account_info')
    op.drop_table('customers_info')
    op.create_unique_constraint(None, 'transaction_info', ['transaction_id'])
    op.drop_constraint('transaction_info_ibfk_3', 'transaction_info', type_='foreignkey')
    op.drop_constraint('transaction_info_ibfk_2', 'transaction_info', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_info_ibfk_2', 'transaction_info', 'account_info', ['cust_id'], ['cust_id'])
    op.create_foreign_key('transaction_info_ibfk_3', 'transaction_info', 'customers_info', ['receiver_id'], ['cust_id'])
    op.drop_constraint(None, 'transaction_info', type_='unique')
    op.create_table('customers_info',
    sa.Column('cust_id', mysql.INTEGER(display_width=10), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('city', mysql.TEXT(), nullable=False),
    sa.Column('state', mysql.TEXT(), nullable=False),
    sa.Column('pin_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.TEXT(), nullable=False),
    sa.Column('phone_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cust_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account_info',
    sa.Column('acc_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cust_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activation_date', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('total_bal', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customers_info.cust_id'], name='account_info_ibfk_1'),
    sa.PrimaryKeyConstraint('acc_no'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('cust', 'account_info', ['cust_id'], unique=False)
    # ### end Alembic commands ###
